Zen 55
Kozea/www-teepy pull request #56
Opened 2022-06-23 10:02 UTC by annabellou

Voici la PR concernant le ticket https://github.com/Kozea/teepy/issues/2024#issuecomment-1163062428 pour l'ajout de l'offre zen pour la période estivale. Je me suis permis d'ajouter le nouvel objet de mail "offre zen" dans le select du formulaire de contact, il faudrait bien vérifier que je n'ai pas fait d'erreur 😅 Merci !

2022-06-23 17:14 UTC, gentooboontoo requested changes

2022-06-23 17:16 UTC, gentooboontoo approved these changes

2022-06-24 07:52 UTC, annabellou commented on sass/style.sass
> +  text-align: center
En effet, c'est supprimé !

2022-06-24 07:53 UTC, annabellou commented on sass/style.sass
> +  width: 100%
Pareil, supprimé !

2022-06-24 07:53 UTC, annabellou commented on sass/style.sass
> +    flex-wrap: wrap
Pareil, supprimé !

2022-06-24 07:54 UTC, annabellou commented on sass/style.sass
> +      margin: auto
Celui-ci reste en revanche, sans le `margin: auto`, le logo se déplace en haut du conteneur.

2022-06-24 07:54 UTC, merged