Correct optic advantage text + correct typo
Kozea/www-teepy pull request #58
Opened 2022-06-29 08:12 UTC by annabellou

Suite au ticket https://github.com/Kozea/www-teepy/issues/50 : 

- j'ai corrigé le texte concernant "la prise en charge" (demande du ticket)
- et j'en ai profité pour supprimer un point inutile après "économie et gain de productivité"

2022-06-29 08:28 UTC, gentooboontoo requested changes

2022-06-29 08:28 UTC, gentooboontoo commented on templates/optic.html
>      <li id="rationalization-optic"><strong>Rationnalisation</strong> du temps passé en back-office.</li>
Du coup, profitons en pour dégommer le `n` en trop dans `Rationalisation` :wink:

2022-06-30 07:50 UTC, annabellou commented on templates/optic.html
>      <li id="rationalization-optic"><strong>Rationnalisation</strong> du temps passé en back-office.</li>
En effet, quelle horreur 😱 . C'est maintenant corrigé !

2022-06-30 08:05 UTC, gentooboontoo commented on templates/optic.html
>      <li id="rationalization-optic"><strong>Rationnalisation</strong> du temps passé en back-office.</li>
#bleedingeyes :sweat_smile:

2022-06-30 08:06 UTC, gentooboontoo approved these changes
C'est good :+1:

2022-06-30 08:08 UTC, merged